version:"v1"
services:
	image01:
	  image: acmebase
	  ports:
	  - "3306:3306"
	  environment:
	  - MYSQL_ROOT_PASSWORD=123456
	  - MYSQL_USER=root
	  - MYSQL_PASSWORD=123456
	  - MYSQL_DATABASE=testdb
	image02:
      image: acmeprd
	  ports:
	  - "8080:80"
	image03:
	  image: acmedev
	  ports:
	  - "8085:80"

